[workspace]
members = ["./crates/*"]
exclude = ["./vendor/jni-rs"]
resolver = "3"

[workspace.package]
# Keep in sync with ci.yml
rust-version = "1.96.0"
edition = "2024"
license = "AGPL-3"
authors = ["Aime23"]

[workspace.dependencies]
ivpl = { version = "0.1.0", path = "./crates/ivpl"}
ivpl-java = { version = "0.1.0", path = "./crates/ivpl-java"}
ivpl-java-binding = { version = "0.1.0", path = "./crates/ivpl-java-binding"}

jni = { version = "0.22.4", features = ["invocation"], path = "./vendor/jni-rs/crates/jni" }
derive_more = { version = "2.1.1", features = ["into", "from"] }
infrarust-api = { git = "https://github.com/Shadowner/Infrarust.git", tag = "v2.0.0-beta.1" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = "1.22.0"
zip = { version = "8.3.1"}
serial_test = "3.4.0"
