[package]
name = "ivpl"
version = "0.1.0"
edition = "2024"

[dependencies]
ivpl-java-binding.workspace = true
infrarust-api.workspace = true
derive_more.workspace = true
jni.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
serial_test.workspace = true
